services:
  holidaycheck:
    build:
      context: https://github.com/mschoettli/holidaycheck.git#main
      dockerfile: Dockerfile
    container_name: holidaycheck
    ports:
      - "${HOLIDAYCHECK_PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      HOST: "0.0.0.0"
      PORT: "3000"
    restart: unless-stopped
